// =============================================================================
// EXAMPLE — the entity list of a connector.
// Exactly the same pattern as datacubeapp (rayfin/connectors/datacubewarehouse/schema.ts).
//
// 👉 Put it in: rayfin/connectors/<connectorName>/schema.ts
//    (replacing the placeholder schema.ts generated by `rayfin connector add`)
//
// Adding a new table = 3 lines: the import, an entry in `entities`, and one in
// the type below. The name here = the name used in data.ts:
//   client.connectors.<connectorName>.RevenueMonthly.findMany()
//
// ⚠️ IMPORTANT: every registered entity MUST exist as a table in the
// warehouse. If even one is missing, the warehouse rejects the ENTIRE connector
// and every chart fails to load data (not just that table's chart).
// =============================================================================

import type { GraphQLBackedConnector } from '@microsoft/rayfin-connector-fabric-graphql';
import type { ConnectorConfig } from '@microsoft/rayfin-connectors';

import { RevenueMonthly } from './RevenueMonthly.js';

export { RevenueMonthly } from './RevenueMonthly.js';

// Subset: only the summary tables the dashboard reads. Read-only connector.
export const connectorConfig = {
  connector: 'fabric-warehouse',
  operations: ['read'],
  entities: {
    RevenueMonthly,
  },
} as const satisfies ConnectorConfig;

// 👉 CHANGE HERE: the type name can be anything; it's used in src/lib/connectors.ts.
export type WarehouseSchema = GraphQLBackedConnector<
  {
    RevenueMonthly: typeof RevenueMonthly;
  },
  typeof connectorConfig
>;
